config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :appointments, except: [:destroy]
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'home#index'
    end
    
    unauthenticated do
      root to: 'devise/sessions#new'
    end
  end

  devise_scope :admin_user do
    authenticated :admin_user do
      root to: 'admin/dashboard#index'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :service
  before_save :set_end
  before_update :set_end

  scope :of_date,             -> (date) { where(start: date.all_day).order(start: :desc) }
  scope :from_user,           -> (user_id) { where(user_id: user_id) }
  scope :future_appointments, -> { where('start >= ?', Date.today.beginning_of_day).order(start: :desc) }
  scope :past_appointments,   -> { where('start < ?', Date.today.beginning_of_day).order(start: :desc) }

  def client_name
    self.user.present? ? self.user.name : "Usuario borrado"
  end

  def service_name
    self.service.name
  end

  def duration_in_minutes
    self.service.duration.minutes
  end

  def client_phone_number
    self.user.present? ? self.user.phone_number : "Usuario borrado"
  end

  def client_email
    self.user.email
  end

  def formatted_date
    self.start.strftime('%d-%m-%Y')
  end

  def start_time
    self.start.to_s[10..15]
  end

  def end_time
    self.end.to_s[10..15]
  end

  private

  def set_end
    self.end = self.start + self.duration_in_minutes
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :appointments

  def duration_in_minutes 
    self.duration.minutes
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_one_attached :profile_pic
  has_many :appointments, dependent: :nullify
  validates :name, :email, :phone_number, presence: true
  validates :phone_number, format: { with: /\A\+56[0-9]{9}\z/, message: 'no es válido. Ingresa un número chileno con el formato "+56XXXXXXXXX"'  }
  before_save :capitalize_names

  def profile_pic_url
    self.profile_pic.attachment.service_url
  end

  private

  def capitalize_names
    self.name = self.name.titlecase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :profile_pic])
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_services, only: [:new, :edit]
  before_action :set_available_hours, only: [:new, :edit]

  # GET /appointments
  # GET /appointments.json
  def index
    respond_to do |format|
      format.html do
        @future_appointments = Appointment.from_user(current_user).future_appointments
        @past_appointments = Appointment.from_user(current_user).past_appointments
      end
      format.json { @appointments = Appointment.all }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    redirect_to root_path, alert: '¡Ups! No deberías estar haciendo eso.' if @appointment.user_id != current_user.id
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new

    if params[:date].present? && params[:service_id].present?
      result = DateGetter.new('11:00', '19:00', params[:date], params[:service_id]).get_possible_dates
      render json: result
    end
  end

  # GET /appointments/1/edit
  def edit
    redirect_to root_path, alert: '¡Ups! No deberías estar haciendo eso.' if @appointment.user_id != current_user.id

    if params[:date].present?

      result = DateGetter.new('11:00', '19:00', params[:date], params[:service_id]).get_possible_dates
      render json: result
    end
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user = current_user

    respond_to do |format|
      if @appointment.save
        AppointmentMailer.with(appointment: @appointment).confirmation.deliver_now

        format.html { redirect_to @appointment, notice: '¡Tu cita fue agendada exitosamente!' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        @appointment.update(end: @appointment.start + @appointment.duration_in_minutes)
        format.html { redirect_to @appointment, notice: 'La cita fue actualizada con éxito.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'La cita fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def set_services
      @services = Service.all
    end

    def set_available_hours
      @available_hours = [
        '11:00', '11:30', '12:00', '12:30', '13:00', '13:30', '14:00', '14:30', '15:00', '15:30', '16:00',
        '16:30', '17:00', '17:30', '18:00', '18:30', '19:00'
      ]
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:start, :service_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <div>
    <p class="font-weight-bold container">Selecciona el tipo de servicio y fecha de tu cita</p>
    <% if appointment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(appointment.errors.count, "error") %> prohibieron que esta cita se guardara:</h2>

        <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="d-flex">
      <div class="container d-flex flex-column">
        <div class="field d-flex justify-content-between">
          <%= form.label :service_id, "Tipo de servicio:" %>
          <%= form.collection_select(:service_id, @services, :id, :name, {}, {class: "custom-select"}) %>
        </div>

        <div class="field d-flex justify-content-between">
          <%= form.label :date, "Fecha:" %>
          <div class="d-flex"><%= form.date_select :date, {}, {class: "custom-select"} %></div>
        </div>

      <button id="get-available-hours" class="btn btn-success">Consultar horarios<br>disponibles</button>
      </div>

    </div>
  </div>

  <div class="mt-5">
    <p class="font-weight-bold">Elige un horario</p>

    <div id="time-select" class="d-flex flex-column p-3">
      <div class="d-flex justify-content-between">
        <label class="mr-5" for="appointment_start">Horarios:</label>
        <select name="appointment[start]" id="appointment_start" class="custom-select" required>
          <option selected value="">Selecciona</option>
        </select>
      </div>

      <%= form.submit "¡Agendar!", class: "my-3 p-3 font-weight-bold btn btn-info" %>
    </div>
  </div>

<% end %>

app/views/appointments/edit.html.erb
<%= provide :new_appointment, "active" %>

<h2 class="ml-5">Reagendando cita:
</h2>
<p class="h2 ml-5">
    <%= @appointment.service_name %>
    el <%= @appointment.formatted_date %>
    a las <%= @appointment.start_time %>
</p>


<div class="d-flex flex-column-reverse flex-md-row justify-content-around">
    <div class="mx-auto" id="calendar"></div>
    <div class="mx-auto pb-5">
        <%= render 'form', appointment: @appointment %>
    </div>
</div>

<%= link_to 'Volver atrás', :back, class: "btn btn-outline-dark font-weight-bold mt-3 ml-5 px-5" %>

<script>
    renderCalendar();
    getAvailableHours();
</script>

app/views/appointments/index.html.erb
<%= provide :appointments, "active" %>

<div>
  <h3 class="ml-3">Próximas citas:</h3>

  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>Fecha</th>
        <th>Horario</th>
        <th>Tipo de servicio</th>
        <th>Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @future_appointments.each do |appointment| %>
        <tr>
          <td><%= appointment.formatted_date %></td>
          <td><%= appointment.start_time %> - <%= appointment.end_time %></td>
          <td><%= appointment.service_name %></td>
          <td><%= link_to 'Reagendar', edit_appointment_path(appointment) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "Agendar nueva cita", new_appointment_path, class: "container btn btn-success py-2 mb-4 font-weight-bold d-block" %>

  <h2 class="ml-3">Citas pasadas:</h2>

  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>Fecha</th>
        <th>Hora de inicio</th>
        <th>Tipo de servicio</th>
        <th>Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @past_appointments.each do |appointment| %>
        <tr>
          <td><%= appointment.formatted_date %></td>
          <td><%= appointment.start_time %> - <%= appointment.end_time %></td>
          <td><%= appointment.service_name %></td>
          <td><%= link_to 'Reagendar', edit_appointment_path(appointment) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/appointments/new.html.erb
<%= provide :new_appointment, "active" %>

<div class="d-flex flex-column flex-md-row justify-content-around">
    <div class="mx-auto pb-4" id="calendar"></div>
    <div class="mx-auto pb-5">
        <%= render 'form', appointment: @appointment %>
    </div>
</div>

<script>
    renderCalendar();
    getAvailableHours();
    resetHoursSelect();
</script>

app/views/appointments/show.html.erb
<div class="ml-5">
  <h2 class="mb-4">¡Muchas gracias!</h2>

  <p>
    <strong>Tipo de servicio:</strong>
    <%= @appointment.service_name %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= @appointment.formatted_date %>
  </p>

  <p>
    <strong>Hora de inicio:</strong>
    <%= @appointment.start_time %>
  </p>

  <p>
    <strong>Hora de término estimada:</strong>
    <%= @appointment.end_time %>
  </p>

  <%= link_to 'Volver al principio', root_path, class: "btn btn-info font-weight-bold mt-3" %>
</div>

app/views/home/index.html.erb
<%= provide :home, "active" %>

<div class="container">
  <h3>¡Bienvenid@, <%= current_user.name %>!</h3>

  <div id="profile-pic">
    <% avatar_url = current_user.profile_pic.attachment.nil? ? image_path("default-avatar.png") : current_user.profile_pic_url %>
    <img class="w-100" src="<%= avatar_url %>" alt="Foto de perfil">
  </div>

  <div class="my-4 text-center d-flex flex-column">
    <%= link_to "¡Agenda una cita aquí!", new_appointment_path, class: "btn btn-success py-3 font-weight-bold" %>
    <p class="my-4">. . . ó</p>
    <a class="btn btn-info py-3" href="https://wa.link/mdi962" target="blank">Contáctame directamente por WhatsApp</a>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<div class="mt-4">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Ingresar con una cuenta ya existente", new_session_path(resource_name) %><br>
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Registrarse", new_registration_path(resource_name) %><br>
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "¿Olvidaste tu contraseña?", new_password_path(resource_name) %><br>
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "¿No recibiste las intrucciones de confirmación?", new_confirmation_path(resource_name) %><br>
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "¿No recibiste las intrucciones de desbloqueo?", new_unlock_path(resource_name) %><br>
  <% end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Ingresa con #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br>
    <% end %>
  <% end %>

</div>